# Generated by Django 4.0.2 on 2022-02-16 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='max_discount',
            field=models.PositiveIntegerField(blank=True, help_text='Enter max amount of discount', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload photo of product here', null=True, upload_to='media/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_in_inventory',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
