# Generated by Django 4.0.2 on 2022-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Unkown', max_length=100),
        ),
    ]
